spring:
  application:
    name: @artifactId@
  profiles:
    active: @profiles.active@
  datasource:
    url: jdbc:mysql://39.103.174.251:3366/spring_security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: root
server:
  port: 20000
