again:
  boot:
    starter:
      es:
        host: 192.168.1.175
        port: 9200
        index: wscrm_message
        type: message
        cluster_name: scrm-es
        user_name:
        password: